### PR TITLE
feat: implement app events

### PR DESCRIPTION
**Pull request by filipporomani**
Added app events support and docs. 

Addressing #65.

### CODE REVIEW

**Comment by soerenetler** [comment]
I like integrating this in the heyoo library. But personally I think I will not be using it, because I mostly run heyoo in severless functions. As long as the two ways are possible I am fine with it.
In general I feel the one WhatsApp Class is getting a little bloated. I would like to split up in WhatsAppClient and WhatsAppUpdate #32.

**Comment by filipporomani** [comment]
I'll work on it if it's fine for you.

**Comment by soerenetler** [comment]
I do already have a typed WhatsAppUpdate Clss in another project. I can transfer it o heyoo and then it needs some more testing and improvements. I think the event based approach could be implemented seperatly. The separation of Client and Update Class could introduce breaking changes to the library.

**Comment by filipporomani** [comment]
Closing #87 as wontfix.

**Pull request closed without merging**
