### PR TITLE
Various dependencies & setup fixes

### PR DESCRIPTION
**Pull request by filipporomani**
- Removed unused dependencies: Flask was inserted into setup.py, even if it's not used by heyoo. Flask is used by Docker, but should not be inserted in the setup.py file. 
- Added missing dependencies: colorama and typing. They were not in the setup.py file, and this could result in errors while running. 
- Fixed description: now the setup.py file uses the README file as long description. This makes everything easier, as the description is updated on a new release.
- Grammar fix in setup.py.
- Removed useless temp files.

### CODE REVIEW

**Comment by Kalebu** [comment]
Hey @filipporomani 

May I ask Why did you close this patch? I think I am pretty useful indeed

**Comment by filipporomani** [comment]
I actually can't remember this. Good question. Sorry for the issue. I am reopening this rn. 

Also: I actually made a fork of the repo and made many changes, is it ok if I create some PRs with the changes I made in the other repo?

**Review by Kalebu — APPROVED** [review]
Great work, Nice cleanup @filipporomani

**Comment by filipporomani** [comment]
Thanks! Glad to help!

**Pull request merged**
