### PR TITLE
Add support for documents

### PR DESCRIPTION
**Pull request by taylorgibb**
When sending a document this is the response, this adds a helper method like files and images have to get the document reference so we can download the attachment.

image

### CODE REVIEW

**Comment by taylorgibb** [comment]
Tested as below, works well, can we get this merged in so i can update our package from pip ? 

image

**Comment by Kalebu** [comment]
Hi @taylorgibb 

Thanks for taking your time to contribute 

Merging this

**Comment by taylorgibb** [comment]
Thank you so much, much appreciated! Thanks for the work on this library as well!

**Comment by taylorgibb** [comment]
@Kalebu any idea when you will be able to publish this to pip ?

**Comment by Kalebu** [comment]
There was no definite like circle to publish to PyPI but I will definitely do it this week 

Have two questions ASAP

1. Does this pull request also fix issue #45 
2.  Do you also have spare time to work on #43?

Thank you @taylorgibb

**Comment by taylorgibb** [comment]
Yes it does fix #45 but i suppose i should update the docs and the sample hook as well. Ill send a separate PR for that later today as there is not concept of message_type file anymore, Whatsapp is now sending them as message_type document. 

I can take a look at #43, i just want to get our project over the line first.

**Pull request merged**
