### PR TITLE
add mark_as_read

### PR DESCRIPTION
**Pull request by filipporomani**
Added mark_as_read function to mark messages as read using the message's ID.

### CODE REVIEW

**Review by Kalebu — COMMENTED** [review]
@filipporomani  Thank you for the update 

Can you make the base URL on __init__() so that its easier to change the versions

**Comment by filipporomani** [comment]
Sure! I'll add another commit once I'm back home!

**Comment by filipporomani** [comment]
Done! I just commited the change!

**Review by Kalebu — APPROVED** [review]
Thank you @filipporomani  merging this

**Pull request merged**
