### PR TITLE
added button for auto deployment of webhook to Heroku platform

### PR DESCRIPTION
**Pull request by JAXPARROW**

### CODE REVIEW

**Comment by Kalebu** [comment]
Hi @JAXPARROW 

This is definitely going to help a lot of people with hook setup 

Thank you for you're awesome contribution

Merged !!!

**Comment by Kalebu** [comment]
Hi @JAXPARROW 

Can you also please clarify on how people can edit their own **TOKEN** and **VERIFY TOKEN** before deploying the webhook to heroku 

Something like they gotta fork first your hook, update it and deploy to heroku 

Let me know what you think

**Comment by JAXPARROW** [comment]
> Hi @JAXPARROW
> 
> Can you also please clarify on how people can edit their own **TOKEN** and **VERIFY TOKEN** before deploying the webhook to heroku
> 
> Something like they gotta fork first your hook, update it and deploy to Heroku
> 
> Let me know what you think

Hi Kalebu,

There's no need for them to fork or update anything before pushing it to Heroku, the TOKEN is the random string which they are going to input the key and value pair in the Heroku dashboard.

**Comment by JAXPARROW** [comment]
> > Hi @JAXPARROW
> > Can you also please clarify on how people can edit their own **TOKEN** and **VERIFY TOKEN** before deploying the webhook to heroku
> > Something like they gotta fork first your hook, update it and deploy to Heroku
> > Let me know what you think
> 
> Hi Kalebu,
> 
> There's no need for them to fork or update anything before pushing it to Heroku, the TOKEN is the random string which they are going to input the key and value pair in the Heroku dashboard.

Documentation Updated, let me know if it is still easier to follow. 😎😎😎😎

**Pull request merged**
