### PR TITLE
fix: remove templatev2 (useless)

### PR DESCRIPTION
**Pull request by filipporomani**
Please refer to issue #73.

### CODE REVIEW

**Comment by filipporomani** [comment]
Fixed issues #73 & #69.

**Comment by Kalebu** [comment]
Hi @filipporomani 

Thank you for contributing 

> You're not supposed to completely remove `send_template_v2`, we want to add a `deprecation` warning first and then have a version to remove it completely as some people already use it.

**Comment by filipporomani** [comment]
ooook, i'll go ahead and fix this.

**Comment by filipporomani** [comment]
Should be fine now

**Review by Kalebu — CHANGES_REQUESTED** [review]
You need to add the warning within the heyoo `send_templatev2` method more of something like this 

```python
import warnings
from colorama import Fore, Style

def send_templatev2(self, template, recipient_id, components, lang: str = "en_US"):
    message = f"{Fore.RED}The 'send_templatev2' method is deprecated and will be removed in the future. Please use 'send_template' instead.{Style.RESET_ALL}"
    warnings.warn(message, DeprecationWarning)
    return send_template(template, recipient_id, components, lang=lang)
```

**Comment by filipporomani** [comment]
Commited a patch.

**Review by filipporomani — COMMENTED** [review]
Push requested changes

**Review by Kalebu — APPROVED** [review]

**Pull request merged**
