### PR TITLE
refactor: update API to v17

### PR DESCRIPTION
**Pull request by filipporomani**
No breaking changes involved. 

Tested up to v15, works fine. 
From v15 to v17 there are no breaking changes (as said in the Facebook API docs).

### CODE REVIEW

**Comment by soerenetler** [comment]
I think the version should be a parameter when initializing the client. Default could be v17, but maybe some people want to change this and use older versions. This might be especially useful in the future when there are breaking change. But I agree that there should only be one `base_url`. Thank you for the PR :)

**Comment by filipporomani** [comment]
The problem could be with a possible error handler. 
Or we'll keep an error handler for versions <16 and one for versions >=16 or there will probably be some issues. 

Btw yeah, I agree that the user should decide.

**Comment by soerenetler** [comment]
I think we should only implement a new error handler for version <=16 for now.
Great :)

**Comment by filipporomani** [comment]
Not easy for v <16, but can be done. I'm already working on one for v>=16. 

Idk if I'll be able to finish it, cause I'll work full time the whole summer.

**Comment by filipporomani** [comment]
Closing #88 as wontfix

**Pull request closed without merging**
